"""
LexQueryia Backend — FastAPI server for Legal Query RAG Pipeline
"""

import os
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

from rag_pipeline import query_legal_rag

app = FastAPI(
    title="LexQueryia API",
    description="AI-powered Legal Query System with RAG pipeline for Indian Law",
    version="1.0.0",
)

# CORS — allow the Vite dev server
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class QueryRequest(BaseModel):
    query: str
    session_id: str | None = None


class Citation(BaseModel):
    id: int
    actName: str
    section: str
    title: str
    text: str


class QueryResponse(BaseModel):
    answer: str
    citations: list[Citation]
    disclaimer: str


DISCLAIMER = (
    "⚖️ Disclaimer: This response is generated by an AI system for informational and educational "
    "purposes only. It does not constitute professional legal advice. The information provided is "
    "based on statutory texts and may not reflect the most recent amendments or judicial interpretations. "
    "Always consult a qualified legal professional for advice specific to your situation."
)


@app.get("/")
async def root():
    return {"status": "ok", "service": "LexQueryia API", "version": "1.0.0"}


@app.get("/health")
async def health():
    return {"status": "healthy"}


@app.post("/api/query", response_model=QueryResponse)
async def handle_query(request: QueryRequest):
    if not request.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty")

    try:
        result = query_legal_rag(request.query)

        citations = [
            Citation(
                id=i + 1,
                actName=c["act_name"],
                section=c["section"],
                title=c["title"],
                text=c["text"],
            )
            for i, c in enumerate(result["citations"])
        ]

        return QueryResponse(
            answer=result["answer"],
            citations=citations,
            disclaimer=DISCLAIMER,
        )

    except Exception as e:
        print(f"Error processing query: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to process query: {str(e)}")


if __name__ == "__main__":
    import uvicorn

    host = os.getenv("HOST", "0.0.0.0")
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run("main:app", host=host, port=port, reload=True)
